package com.digitaldetective.util;

import com.digitaldetective.analyzer.InvestigationAnalyzer;
import com.digitaldetective.model.FileRecord;
import com.digitaldetective.model.FileType;
import com.digitaldetective.model.Investigation;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Random;

/**
 * Builds a realistic-looking but entirely synthetic {@link Investigation}
 * for "Demo Mode", so the interface can be shown off in a presentation
 * without needing to scan a real folder. No real files are read or
 * created - every path, size, timestamp and hash below is fabricated.
 */
public final class DemoDataGenerator {

    private static final String ROOT = "C:\\Users\\Investigator\\Documents\\DemoCase";
    private static final Random RANDOM = new Random(42); // fixed seed for a repeatable demo

    private DemoDataGenerator() {
    }

    public static Investigation generate() {
        Investigation investigation = new Investigation();
        investigation.setDemo(true);
        investigation.setInvestigationPath(ROOT + "  (DEMO MODE - synthetic data)");
        Instant started = Instant.now().minusSeconds(42);
        investigation.setScanStarted(started);

        investigation.setNotes("Synthetic demonstration dataset generated by Demo Mode for the college "
                + "presentation. No real files were scanned.");

        // ---- Normal, everyday files across categories -------------------------
        add(investigation, "report.docx", "Documents", 245_000, daysAgo(40), daysAgo(2), daysAgo(1), false, false);
        add(investigation, "invoice_march.pdf", "Documents", 182_400, daysAgo(60), daysAgo(60), daysAgo(5), false, false);
        add(investigation, "thesis_draft.docx", "Documents", 1_240_000, daysAgo(20), hoursAgo(3), hoursAgo(1), false, false);
        add(investigation, "meeting_minutes.pdf", "Documents", 98_000, daysAgo(10), daysAgo(10), daysAgo(3), false, false);
        add(investigation, "notes.txt", "Notes", 4_200, daysAgo(5), hoursAgo(6), hoursAgo(2), false, false);

        add(investigation, "vacation_beach.jpg", "Photos\\2025", 3_400_000, daysAgo(200), daysAgo(200), daysAgo(30), false, false);
        add(investigation, "screenshot_bug.png", "Photos\\Screenshots", 820_000, daysAgo(3), daysAgo(3), daysAgo(1), false, false);
        add(investigation, "company_logo.svg", "Assets", 45_000, daysAgo(300), daysAgo(120), daysAgo(60), false, false);
        add(investigation, "profile_picture.png", "Photos", 512_000, daysAgo(90), daysAgo(90), daysAgo(10), false, false);

        add(investigation, "demo_recording.mkv", "Videos", 1_920_000_000L, daysAgo(15), daysAgo(15), daysAgo(4), false, false);
        add(investigation, "presentation_practice.mp4", "Videos", 640_000_000L, daysAgo(2), daysAgo(2), hoursAgo(5), false, false);

        add(investigation, "podcast_episode.wav", "Audio", 88_000_000L, daysAgo(50), daysAgo(50), daysAgo(20), false, false);
        add(investigation, "background_music.mp3", "Audio", 6_400_000, daysAgo(70), daysAgo(70), daysAgo(30), false, false);

        add(investigation, "backup.zip", "Backups", 4_820_000_000L, daysAgo(1), daysAgo(1), hoursAgo(2), false, false);
        add(investigation, "old_project.rar", "Backups\\Archive", 240_000_000L, daysAgo(400), daysAgo(400), daysAgo(90), false, false);
        add(investigation, "database_backup.tar.gz", "Backups", 832_000_000L, daysAgo(7), daysAgo(7), daysAgo(2), false, false);

        add(investigation, "Main.java", "Projects\\digital-detective\\src", 6_100, daysAgo(4), hoursAgo(1), hoursAgo(1), false, false);
        add(investigation, "app.py", "Projects\\scripts", 3_800, daysAgo(12), daysAgo(2), daysAgo(1), false, false);
        add(investigation, "index.html", "Projects\\website", 9_400, daysAgo(25), daysAgo(6), daysAgo(3), false, false);
        add(investigation, "styles.css", "Projects\\website", 5_200, daysAgo(25), daysAgo(6), daysAgo(3), false, false);

        add(investigation, "budget_2026.xlsx", "Finance", 78_000, daysAgo(18), daysAgo(1), hoursAgo(4), false, false);
        add(investigation, "sales_data.csv", "Finance\\Exports", 152_000, daysAgo(9), daysAgo(9), daysAgo(2), false, false);
        add(investigation, "pitch_deck.pptx", "Presentations", 3_100_000, daysAgo(6), daysAgo(1), hoursAgo(3), false, false);

        // ---- Duplicate files (same content in three locations) ----------------
        addDuplicateGroup(investigation, "vacation_photo_final.jpg", 2_450_000,
                new String[]{"Photos\\2025", "Backups\\PhotoBackup", "Old Drive\\Photos"});
        addDuplicateGroup(investigation, "project_report_v2.docx", 310_000,
                new String[]{"Documents", "Backups", "Shared\\TeamFolder"});

        // ---- Empty files --------------------------------------------------------
        add(investigation, "placeholder.txt", "Misc", 0, daysAgo(100), daysAgo(100), daysAgo(100), false, false);
        add(investigation, "empty_log.log", "Logs", 0, daysAgo(2), daysAgo(2), daysAgo(2), false, false);
        add(investigation, "new_document.docx", "Documents", 0, hoursAgo(1), hoursAgo(1), hoursAgo(1), false, false);

        // ---- Hidden files ---------------------------------------------------------
        add(investigation, ".env", "Projects\\digital-detective", 512, daysAgo(30), daysAgo(2), daysAgo(1), true, false);
        add(investigation, ".gitignore", "Projects\\digital-detective", 220, daysAgo(30), daysAgo(30), daysAgo(10), true, false);
        add(investigation, ".DS_Store", "Photos", 6_148, daysAgo(60), daysAgo(5), daysAgo(1), true, false);
        add(investigation, ".secret_notes", "Misc", 1_024, daysAgo(15), daysAgo(15), daysAgo(15), true, true);

        // ---- Potentially suspicious files -----------------------------------------
        add(investigation, "invoice.pdf.exe", "Downloads", 245_000, hoursAgo(5), hoursAgo(5), hoursAgo(1), false, false);
        add(investigation, "photo.jpg.scr", "Downloads", 180_000, hoursAgo(20), hoursAgo(20), hoursAgo(2), false, false);
        add(investigation, "keygen_activator.exe", "Downloads\\Temp", 512_000, hoursAgo(2), hoursAgo(2), hoursAgo(1), true, false);
        add(investigation, "free_password_stealer.exe", "Downloads\\Temp", 890_000, hoursAgo(1), hoursAgo(1), hoursAgo(1), false, false);
        add(investigation, "setup.exe", "Downloads", 12_400_000, daysAgo(2), daysAgo(2), daysAgo(1), false, false);
        add(investigation, "update_tool.bat", "Projects\\scripts", 2_100, daysAgo(4), daysAgo(4), daysAgo(1), false, false);
        add(investigation, "installer.msi", "Downloads", 45_000_000, daysAgo(3), daysAgo(3), daysAgo(1), false, false);

        investigation.setDirectoryCount(19);
        investigation.setScanCompleted(started.plusSeconds(4));

        InvestigationAnalyzer.runAll(investigation);
        return investigation;
    }

    private static void add(Investigation inv, String name, String folder, long size,
                             Instant created, Instant modified, Instant accessed, boolean hidden, boolean readOnly) {
        FileRecord r = new FileRecord();
        r.setFileName(name);
        String path = ROOT + "\\" + folder + "\\" + name;
        r.setAbsolutePath(path);
        r.setRelativePath(folder + "\\" + name);
        String ext = FileUtils.getExtension(name);
        r.setExtension(ext);
        r.setFileType(FileType.fromExtension(ext));
        r.setSizeBytes(size);
        r.setCreatedTime(created);
        r.setModifiedTime(modified);
        r.setAccessedTime(accessed);
        r.setHidden(hidden);
        r.setReadOnly(readOnly);
        r.setSymbolicLink(false);
        r.setDirectory(false);
        r.setSha256(size == 0 ? "" : fakeHash(path));
        inv.addFile(r);
    }

    private static void addDuplicateGroup(Investigation inv, String name, long size, String[] folders) {
        String sharedHash = fakeHash("duplicate::" + name + size);
        for (String folder : folders) {
            FileRecord r = new FileRecord();
            r.setFileName(name);
            String path = ROOT + "\\" + folder + "\\" + name;
            r.setAbsolutePath(path);
            r.setRelativePath(folder + "\\" + name);
            String ext = FileUtils.getExtension(name);
            r.setExtension(ext);
            r.setFileType(FileType.fromExtension(ext));
            r.setSizeBytes(size);
            Instant t = daysAgo(RANDOM.nextInt(30) + 1);
            r.setCreatedTime(t);
            r.setModifiedTime(t);
            r.setAccessedTime(t);
            r.setSha256(sharedHash);
            inv.addFile(r);
        }
    }

    private static String fakeHash(String seed) {
        // Deterministic pseudo-hash for demo purposes only - NOT a real SHA-256 of any content.
        Random r = new Random(seed.hashCode());
        StringBuilder sb = new StringBuilder(64);
        String hex = "0123456789abcdef";
        for (int i = 0; i < 64; i++) {
            sb.append(hex.charAt(r.nextInt(16)));
        }
        return sb.toString();
    }

    private static Instant daysAgo(int days) {
        return Instant.now().minus(days, ChronoUnit.DAYS);
    }

    private static Instant hoursAgo(int hours) {
        return Instant.now().minus(hours, ChronoUnit.HOURS);
    }
}
